#if defined _escalation_objects_included
#endinput
#endif
#define _escalation_objects_included

#include<Escalation_WeaponInfo>
#include<Escalation_WeaponInfoManager>
#include<Escalation_UpgradeMenuCache>
#include<Escalation_PlayerData>
#include<Escalation_UpgradeData>
#include<Escalation_UpgradeDataStore>
#include<Escalation_ClassInfoStore>
#include<Escalation_PlayerAttributeManager>
#include<Escalation_WeaponAttributes>
#include<Escalation_UpgradeDescriptions>
#include<Escalation_BannedUpgrades>
#include<Escalation_LevelData>
#include<Escalation_StockAttributes>